#! /usr/bin/env python3

import subprocess
import os
import sys
import glob


if __name__ == '__main__':
    palettepath = sys.argv[1]
    path = sys.argv[2]

    for fpath in glob.glob(os.path.join(path, '*.mp4')):
        outpath = os.path.splitext(fpath)[0] + '.gif'
        if os.path.isfile(outpath):
            continue
        print(fpath, 'to', outpath)
        try:
            cmd = 'ffmpeg -i {infile} -i {palette} -filter_complex "fps=24,scale=320:-1:flags=lanczos[x];[x][1:v]paletteuse" {outfile}'
            cmd = cmd.format(infile=fpath, outfile=outpath, palette=palettepath)
            subprocess.check_call(cmd, shell=True)
        except Exception as e:
            print(e)
            continue
